### ISSUE TITLE
Version 0.1.3 crashes if security key is needed but not found

### ISSUE THREAD

**Issue by houglum** [google/pyu2f#13]
I've been adding reauth support to gsutil, and found this failure when running our release tests:

Example failure, using version 0.1.3 with the google-reauth-python package (0.1.0) -- see the last couple of lines of this stack trace:

```
Please insert your security key and press enter...DEBUG: Exception stack trace:
    Traceback (most recent call last):
      File "C:\path-to-gsutil\gsutil\gslib\__main__.py", line 576, in _RunNamedCommandAndHandleException
s
        user_project=user_project)
      File "C:\path-to-gsutil\gsutil\gslib\command_runner.py", line 318, in RunNamedCommand
        return_code = command_inst.RunCommand()
      File "C:\path-to-gsutil\gsutil\gslib\commands\ls.py", line 517, in RunCommand
        bucket_fields=bucket_fields):
      File "C:\path-to-gsutil\gsutil\gslib\wildcard_iterator.py", line 456, in IterBuckets
        for blr in self._ExpandBucketWildcards(bucket_fields=bucket_fields):
      File "C:\path-to-gsutil\gsutil\gslib\wildcard_iterator.py", line 375, in _ExpandBucketWildcards
        provider=self.wildcard_url.scheme):
      File "C:\path-to-gsutil\gsutil\gslib\boto_translation.py", line 232, in ListBuckets
        buckets_iter = provider_uri.get_all_buckets(headers=headers)
      File "C:\path-to-gsutil\gsutil\third_party\boto\boto\storage_uri.py", line 585, in get_all_buckets

        return conn.get_all_buckets(headers)
      File "C:\path-to-gsutil\gsutil\third_party\boto\boto\s3\connection.py", line 443, in get_all_bucke
ts
        response = self.make_request('GET', headers=headers)
      File "C:\path-to-gsutil\gsutil\third_party\boto\boto\s3\connection.py", line 671, in make_request
        retry_handler=retry_handler
      File "C:\path-to-gsutil\gsutil\third_party\boto\boto\connection.py", line 1071, in make_request
        retry_handler=retry_handler)
      File "C:\path-to-gsutil\gsutil\third_party\boto\boto\connection.py", line 927, in _mexe
        request.authorize(connection=self)
      File "C:\path-to-gsutil\gsutil\third_party\boto\boto\connection.py", line 377, in authorize
        connection._auth_handler.add_auth(self, **kwargs)
      File "C:\path-to-gsutil\gsutil\third_party\gcs-oauth2-boto-plugin\gcs_oauth2_boto_plugin\oauth2_pl
ugin.py", line 44, in add_auth
        self.oauth2_client.GetAuthorizationHeader())
      File "C:\path-to-gsutil\gsutil\third_party\gcs-oauth2-boto-plugin\gcs_oauth2_boto_plugin\oauth2_cl
ient.py", line 366, in GetAuthorizationHeader
        return 'Bearer %s' % self.GetAccessToken().token
      File "C:\path-to-gsutil\gsutil\third_party\gcs-oauth2-boto-plugin\gcs_oauth2_boto_plugin\oauth2_cl
ient.py", line 332, in GetAccessToken
        access_token = self.FetchAccessToken(rapt_token=rapt)
      File "C:\path-to-gsutil\gsutil\third_party\retry-decorator\retry_decorator\retry_decorator.py", li
ne 20, in f_retry
        return f(*args, **kwargs)
      File "C:\path-to-gsutil\gsutil\third_party\gcs-oauth2-boto-plugin\gcs_oauth2_boto_plugin\oauth2_cl
ient.py", line 622, in FetchAccessToken
        credentials.refresh(http)
      File "C:\path-to-gsutil\gsutil\third_party\oauth2client\oauth2client\client.py", line 545, in refr
esh
        self._refresh(http)
      File "C:\path-to-gsutil\gsutil\third_party\oauth2client\oauth2client\client.py", line 749, in _ref
resh
        self._do_refresh_request(http)
      File "C:\path-to-gsutil\gsutil\third_party\google-reauth-python\google_reauth\reauth_creds.py", li
ne 120, in _do_refresh_request
        headers=headers))
      File "C:\path-to-gsutil\gsutil\third_party\google-reauth-python\google_reauth\reauth.py", line 284
, in refresh_access_token
        scopes=scopes,
      File "C:\path-to-gsutil\gsutil\third_party\google-reauth-python\google_reauth\reauth.py", line 192
, in get_rapt_token
        requested_scopes=scopes)
      File "C:\path-to-gsutil\gsutil\third_party\google-reauth-python\google_reauth\reauth.py", line 139
, in _obtain_rapt
        msg = _run_next_challenge(msg, http_request, access_token)
      File "C:\path-to-gsutil\gsutil\third_party\google-reauth-python\google_reauth\reauth.py", line 88,
 in _run_next_challenge
        client_input = c.obtain_challenge_input(challenge)
      File "C:\path-to-gsutil\gsutil\third_party\google-reauth-python\google_reauth\challenges.py", line
 111, in obtain_challenge_input
        print_callback=sys.stderr.write)
      File "C:\path-to-gsutil\gsutil\third_party\pyu2f\pyu2f\convenience\authenticator.py", line 46, in
Authenticate
        print_callback)
      File "C:\path-to-gsutil\gsutil\third_party\pyu2f\pyu2f\convenience\localauthenticator.py", line 39
, in Authenticate
        six.input()
    AttributeError: 'module' object has no attribute 'input'

'module' object has no attribute 'input'
```

**Comment by jiangk** [comment]
Thanks for the fix!
